# CLASSIFICATION

Usado para asignar o clasificar valores.

### Steps

* Crear el modelo
* Entrenamos al modelo
* Damos datos sin etiquetar
* Modelo predice labels de la data

### Algoritmo k-Nearest Neighbors

Se apoya en el uso de Datapoints, para realizar una predicción, se basa en la similitud de la distancia entre los datapoints existentes para observar la similitud entre estos mismos y así poder hacer una predicción.

In [12]:
from sklearn.neighbors import KNeighborsClassifier

In [1]:
import pandas as pd

In [2]:
dataset = pd.read_csv('telecom_churn_clean.csv')

In [3]:
print(dataset.head())

   Unnamed: 0  account_length  area_code  international_plan  voice_mail_plan  \
0           0             128        415                   0                1   
1           1             107        415                   0                1   
2           2             137        415                   0                0   
3           3              84        408                   1                0   
4           4              75        415                   1                0   

   number_vmail_messages  total_day_minutes  total_day_calls  \
0                     25              265.1              110   
1                     26              161.6              123   
2                      0              243.4              114   
3                      0              299.4               71   
4                      0              166.7              113   

   total_day_charge  total_eve_minutes  total_eve_calls  total_eve_charge  \
0             45.07              197.4             

In [9]:
X= dataset[['total_day_charge','total_eve_charge']].values

In [14]:
print(X)

[[45.07 16.78]
 [27.47 16.62]
 [41.38 10.3 ]
 ...
 [30.74 24.55]
 [36.35 13.57]
 [39.85 22.6 ]]


In [8]:
y= dataset[['churn']].values

In [15]:
print(y)

[[0]
 [0]
 [0]
 ...
 [0]
 [0]
 [0]]


Definimos la forma de la matriz (filas,columnas)

In [10]:
print(X.shape,y.shape)

(3333, 2) (3333, 1)


Especificamos la cantidad de vecinos que se utilizarán para la clasificación.


La cantidad de vecinos que podremos usar dependerá de la cantidad de datos que vayamos a evaluar.

Se recomienda que para determinar la cantidad de vecinos a usar para evaluar el modelo, se determine sacando la raiz cuadrada del número o cantidad de datos que tenemos, en el siguiente ejemplo:

In [21]:
print(len(X))

3333


In [19]:
import math

In [22]:
print(math.sqrt(3333))

57.73214009544424


In [34]:
knn = KNeighborsClassifier(n_neighbors=58)

Entrenamos al modelo.

In [35]:
knn.fit(X,y)

/Users/edu/anaconda3/lib/python3.11/site-packages/sklearn/neighbors/_classification.py:228: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


KNeighborsClassifier(n_neighbors=58)

Predecimos

In [36]:
predictions = knn.predict(X)

In [37]:
print(predictions)

[0 0 0 ... 0 0 0]


In [39]:
import numpy as np

In [40]:
X_new = np.array([[56.8,17.5],
                  [24.4,24.1],
                  [50.1,10.9]])

In [42]:
print(X_new.shape)

(3, 2)


In [43]:
predictions_Xnew = knn.predict(X_new)

In [44]:
print(predictions_Xnew)

[1 0 0]


In [46]:
print(f'Predicciones {predictions_Xnew}')

Predicciones [1 0 0]
